name: Build process
on:
  workflow_dispatch:
    inputs:
      prs:
        description: 'List of patches. Comma separated'
        required: true
        default: ""

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - id: list_prs
        run: echo "prs={${{ input.prs }}}" >> "$GITHUB_OUTPUT"
    outputs:
      prs: ${{ steps.list_prs.outputs.prs }}
    
  approve:
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      matrix:
        prs: ${{ fromJson(needs.validate.output.prs) }}
    steps:
      - run: echo ${{ matrix.prs }}